### PR TITLE
ARC-1341 Fix Flake8 linting errors

### PR DESCRIPTION
**Pull request by ryantimjohn**

### CODE REVIEW

**Comment by ryantimjohn** [comment]
Alright @Frydafly, I fixed all the linting errors and made it fail if we get any new ones. I think I should rewrite create_or_update_standard_models but... not today.

**Comment by ryantimjohn** [comment]
I haven't actually tested that everything runs, will do this on Monday.

**Comment by ryantimjohn** [comment]
Aright, this is ready to review, happy to walk through @Frydafly

**Review by Frydafly — APPROVED** [review]
this is super cool!! I read through it all, and prob my only question is around the changes to the flake8_linter.yml, if you could explain that?

**Comment by ryantimjohn** [comment]
@Frydafly since we're at a zero-error state, I thought the best way to keep us at a zero-error state was to have it fail on all errors. While it may seem silly to have a build fail on, say, a trailing whitespace problem, I think over time it'll make our code a lot cleaner.

**Comment by Frydafly** [comment]
Amazinggggg

All the best,
Fryda
(she/her)

**Pull request merged**
