### PR TITLE
Sprint 3 create mart email deliverability

### PR DESCRIPTION
**Pull request by Frydafly**
- [x] If applicable, add documentation using the `schema.yml` macros documentation with embedded markdown docs (see `mart_email.md` for example) 

- [x] Test branch on a development branch of an existing client (ideally the one that raised the bug). Do this by changing revision of the package to the branch name in `packages.yml` file in dbt State client below.
Habitat test for everyaction

- [X] Re-run `create_or_update_standard_models.py` for the client dbt project, replacing models and dependencies

- [x] check in dbt that client package successfully runs `dbt deps`, `dbt compile`, and `dbt run`; screenshot this page
Screen Shot 2022-10-07 at 2 31 00 PM

- [x] query the resulting staging model in bigquery (or by previewing mart in dbt cloud); screenshot this
Screen Shot 2022-10-07 at 2 58 00 PM

- [x] If exists, link bug issue and jira tickets to PR
https://bluestate.atlassian.net/browse/ARC-1016?atlOrigin=eyJpIjoiZGUyYjI0YjkzY2Y4NGU0YmIxOTg2MDU3YTBhMzVkYmUiLCJwIjoiaiJ9

### CODE REVIEW

**Comment by Frydafly** [comment]
adding @ryantimjohn as second reviewer, because this PR is more complex than usual 

FYI @dmbluestate

**Comment by Frydafly** [comment]
@dmbluestate FINALLY ready for review, truly. it passes. and the table works. 

Pending as a follow up task: 
- copy over models for SFMC
- finish documenting this mart

**Comment by Frydafly** [comment]
done copying over models for SFMC

**Comment by ryantimjohn** [comment]
Sick! I will try and review this over the weekend!

**Comment by Frydafly** [comment]
No worries! And no rush, it’s already working for habitat so we have enough for our demo. So review when you can.

Derrick will also review.

All the best,
Fryda
(she/her)

**Comment by Frydafly** [comment]
documentation is finished as well!

**Review by ryantimjohn — APPROVED** [review]
This is enough code that I'm not able to verify line by line but I queried from the resultant table and everything looked good, then did a cursory check of the files.

**Comment by Frydafly** [comment]
testing this project in bsd-msf now too just to triple check that the sfmc connector works too!

**Comment by Frydafly** [comment]
here it is running in bsd-msf which is an SFMC client yay!

Screen Shot 2022-10-14 at 9 20 55 AM

**Pull request merged**
