### PR TITLE
Create flake8_linter.yml

### PR DESCRIPTION
**Pull request by Frydafly**

### CODE REVIEW

**Comment by Frydafly** [comment]
@ryantimjohn this builds and lints python functions with every PR. what do you think?

**Comment by ryantimjohn** [comment]
Looks good but... I think you're going to have to correct a lot of things to pass first lint =)

**Review by ryantimjohn — APPROVED** [review]
Approved contingent on getting the linter to pass =)

**Comment by Frydafly** [comment]
@ryantimjohn linter finally passed! changes above reflect suggestions by linter. but I also set up a less restrictive workflow that will only error for certain cases, not like... not having a docstring 🙈

**Comment by ryantimjohn** [comment]
I'll be honest: I like the fail conditions after the first go. The first go is hardest </3

**Pull request merged**
