### PR TITLE
ARC-1433-Create-enriched-transaction-unioned-audience-model-based-on-email-name-from-jobs-table

### PR DESCRIPTION
**Pull request by dmbluestate**
# Pull Request for dbt-arc-functions

- [x] If you've created a macro, make sure it is documented by running the notebook: `process_model_documentation_codegen_output.ipynb` util in this repo

- [x] Test branch on a development branch of an existing client (ideally the one that raised the bug). Do this by changing revision of the package to the branch name in `packages.yml` file in dbt State client below.
Client : arc_uusa    Test_branch: testing_ 1433

- [x] If new macro files were created or updated, re-run `create_or_update_standard_models.py` for the client dbt project, replacing models and dependencies

- [x] check in dbt that client package successfully runs `dbt deps`, `dbt compile`, and `dbt run`; screenshot this page
Screenshot 2023-04-17 at 6 15 36 PM

Screenshot 2023-04-17 at 6 15 11 PM

- [x] query the resulting staging model in bigquery (or by previewing mart in dbt cloud, or your IDE); screenshot this
Screenshot 2023-04-17 at 6 15 02 PM

- [x] If exists, link bug issue and jira tickets to PR
https://bluestate.atlassian.net/browse/ARC-1433?atlOrigin=eyJpIjoiMzg4NDg1YjUwOThjNGNmMzgxMTA4N2I3YmUyZjA0YjMiLCJwIjoiaiJ9

### CODE REVIEW

**Comment by dmbluestate** [comment]
@Frydafly, Have no idea why the linter failed. I'm not even sure what it's supposed to be doing. Any context would be great!

**Comment by Frydafly** [comment]
hey! @dmbluestate 

best context is here: https://github.com/bsd/dbt-arc-functions/pull/202

basically, if you install sqlfmt locally and run it in the base directory, the linter will pass. 

it's a formatting linter really, won't change any of the functionality of the code

**Comment by Frydafly** [comment]
@dmbluestate 
1. I think it's a great idea to add to pipfile -- we can make a ticket or issue about that to get it done. let me know if you want to or if I should 
2. I've been running at the base, because otherwise I can't ensure the linter check will pass

**Comment by dmbluestate** [comment]
@Frydafly Ran sqlfmt locally. It formatted the file, but the GitHub check still failed. :( see photo below.

Screenshot 2023-04-18 at 12 37 24 PM

**Comment by Frydafly** [comment]
noting that derrick and I met and we figured out the linting issue.

**Review by Frydafly — CHANGES_REQUESTED** [review]
hello! 

as per our check in, if we can add the audience designation to the "jobs" part of the email mart, (and create a macro within that client macro that turns on if there is a variable set for client name), so that this case when statement applies only to UUSA's stitch implementation and is used for the audience field in our email mart staging tables?

**Comment by dmbluestate** [comment]
> @Frydafly  
By jobs part of the email mart, do you mean adjusting this macro 'mart_email_performance_with_revenue.sql' to add an audience field to the query that uses the case when statement to parse audience name from the email name field? I looked into what we already built, and as long as the mart_email_performance_with_revenue mart is one line per message_id, We already have this data built into the model; the stg_stitch_sfmc_uusa_email_campaigns already has a relation between message id and audience name and this is pulled into the mart_email_performace_with_revenue as campagins.audience. Happy to discuss this further.

 I understand the logic for the client variable part, and I am interested to see how that works when you finish testing.

**Comment by Frydafly** [comment]
> 

OH! got it, @dmbluestate -- thanks, yes if we already have this logic built into the model, then we are good to go. And I will let you know as soon as I have the client variable ready.

**Comment by dmbluestate** [comment]
> @dmbluestate should we close or re-open this PR?

I will close. We will not need this. Thanks for flagging.

**Pull request closed without merging**
