### PR TITLE
patch - changed action field from total_actions to actions and added recurtype field to email

### PR DESCRIPTION
**Pull request by Frydafly**
one line change of `SUM(SAFE_CAST(total_actions AS INT)) AS actions` to `SUM(SAFE_CAST(actions AS INT)) AS actions`

Once I tested in an account other than mercy corps, no other account has any values for `total_actions`
The only consistent actions field is `actions`

EDIT: also pulled in `recurtype` field since it was easy and a part of the development plan for sprint 1

### CODE REVIEW

**Comment by Frydafly** [comment]
now also added recur type as field for bulk vs triggered development

**Comment by Frydafly** [comment]
Screen Shot 2022-08-31 at 10 34 17 AM
dbt run successful in mercycorps

**Comment by Frydafly** [comment]
Screen Shot 2022-08-31 at 10 39 52 AM
production run in mercycorps

**Review by cndege — APPROVED** [review]
Approved!

**Pull request merged**
