### PR TITLE
Document relations_that_match_regex macro

### PR DESCRIPTION
**Pull request by ryantimjohn**
- [x] If applicable, add documentation using the `schema.yml` macros documentation with embedded markdown docs (see `mart_email.md` for example) 

- [x] Test branch on a development branch of an existing client (ideally the one that raised the bug). Do this by changing revision of the package to the branch name in `packages.yml` file in dbt State client below.

- [x] Re-run `create_or_update_standard_models.py` for the client dbt project, replacing models and dependencies

- [x] check in dbt that client package successfully runs `dbt deps`, `dbt compile`, and `dbt run`; screenshot this page

- [x] query the resulting staging model in bigquery (or by previewing mart in dbt cloud); screenshot this

- [x] If exists, link bug issue and jira tickets to PR

### CODE REVIEW

**Comment by ryantimjohn** [comment]
Tested this against the test dashboard:

Screenshot 2022-12-19 at 5 55 00 PM

**Comment by ryantimjohn** [comment]
Fulfills this ticket:
https://bluestate.atlassian.net/browse/ARC-1056?atlOrigin=eyJpIjoiZDVkMjU0YjY0NGEyNDExNjk0MWNlNzVkYTJmMDQyYzIiLCJwIjoiaiJ9
And this issue:
https://github.com/bsd/dbt-arc-functions/issues/95

**Comment by Frydafly** [comment]
Awesome! Looks good!

**Review by Frydafly — APPROVED** [review]
👍

**Pull request merged**
