### PR TITLE
Create stitch sfmc connectors uusa

### PR DESCRIPTION
**Pull request by dmbluestate**
# Pull Request for dbt-arc-functions

- [ ] If you've created a macro, make sure it is documented by running the notebook: `process_model_documentation_codegen_output.ipynb` util in this repo

- [ X] Test branch on a development branch of an existing client (ideally the one that raised the bug). Do this by changing revision of the package to the branch name in `packages.yml` file in dbt State client below.
-  Tested in dbt-arc-uusa.

- [X ] If new macro files were created or updated, re-run `create_or_update_standard_models.py` for the client dbt project, replacing models and dependencies

- [X ] check in dbt that client package successfully runs `dbt deps`, `dbt compile`, and `dbt run`; screenshot this page

Screenshot 2023-03-07 at 7 33 49 PM

Screenshot 2023-03-07 at 7 34 14 PM

Screenshot 2023-03-07 at 7 39 05 PM

- [ X] query the resulting staging model in bigquery (or by previewing mart in dbt cloud, or your IDE); screenshot this
Screenshot 2023-03-07 at 8 11 07 PM

- [ X] If exists, link bug issue and jira tickets to PR
https://bluestate.atlassian.net/browse/ARC-1326?atlOrigin=eyJpIjoiMDRhMzM3NjQ2ZGNiNGQ4ODk1YzAwNTYxOTAwMzMxODAiLCJwIjoiaiJ9

### CODE REVIEW

**Review by Frydafly — COMMENTED** [review]
it runs and looks real good! I have a question on something that might be confusing me -- is the job_id (now message_id) in sfmc a unique ID that exists for each individual email send, like if 1,000 emails are sent would that mean a unique job_id for each of those 1,000 emails, or would it be one job_id corresponding to the deployed email? 

if it's the latter, then we are good to go.

**Comment by Frydafly** [comment]
> it runs and looks real good! I have a question on something that might be confusing me -- is the job_id (now message_id) in sfmc a unique ID that exists for each individual email send, like if 1,000 emails are sent would that mean a unique job_id for each of those 1,000 emails, or would it be one job_id corresponding to the deployed email?
> 
> if it's the latter, then we are good to go.

I just saw in your screenshot above that there were multiple message_id for a given email_id and it made me wonder whether email_id is the appropriate field for message_id instead of job_id? but I'm not familiar enough with sfmc to know!

**Comment by dmbluestate** [comment]
> > it runs and looks real good! I have a question on something that might be confusing me -- is the job_id (now message_id) in sfmc a unique ID that exists for each individual email send, like if 1,000 emails are sent would that mean a unique job_id for each of those 1,000 emails, or would it be one job_id corresponding to the deployed email?
> > if it's the latter, then we are good to go.
> 
> I just saw in your screenshot above that there were multiple message_id for a given email_id, and it made me wonder whether email_id is the appropriate field for message_id instead of job_id. But I'm not familiar enough with sfmc to know!

My understanding is that UUSA uses the job_id as the merge key for revenue attribution, so in that sense, it is the best thing to cast into a message_id. The job_ids are in the transaction source codes and are parsed and used to match revenue to individual emails. My understanding is that email_id may be a way to understand triggered sends or journeys, where multiple emails are sent as a part of a journey. So the email_id would represent the journey or the higher organization level ( like a welcome series) and the job_id would be each unique individual email send. This also gets at how uusa uses sfmc, and I would be interested to see how other clients use it.

Additionally, the other metrics, like clicks, opens, unsubscribes and bounces, all have job_id as the main join key, they don't even have email_id present in the tables.

**Comment by Frydafly** [comment]
> > > it runs and looks real good! I have a question on something that might be confusing me -- is the job_id (now message_id) in sfmc a unique ID that exists for each individual email send, like if 1,000 emails are sent would that mean a unique job_id for each of those 1,000 emails, or would it be one job_id corresponding to the deployed email?
> > > if it's the latter, then we are good to go.
> > 
> > 
> > I just saw in your screenshot above that there were multiple message_id for a given email_id, and it made me wonder whether email_id is the appropriate field for message_id instead of job_id. But I'm not familiar enough with sfmc to know!
> 
> My understanding is that UUSA uses the job_id as the merge key for revenue attribution, so in that sense, it is the best thing to cast into a message_id. The job_ids are in the transaction source codes and are parsed and used to match revenue to individual emails. My understanding is that email_id may be a way to understand triggered sends or journeys, where multiple emails are sent as a part of a journey. So the email_id would represent the journey or the higher organization level ( like a welcome series) and the job_id would be each unique individual email send. This also gets at how uusa uses sfmc, and I would be interested to see how other clients use it.
> 
> Additionally, the other metrics, like clicks, opens, unsubscribes and bounces, all have job_id as the main join key, they don't even have email_id present in the tables.

Got it! So email_id is more of a campaign_id. yep, makes sense to keep job_id as message_id. thanks for the explanation. 

Not relevant to merging this PR, but for my own understanding-- is job_id present in bbcrm and fundraise up? will that be the joining key, or will it be source_code? 

I'll go ahead and approve this!

**Review by Frydafly — APPROVED** [review]
👍

**Pull request merged**
