### PR TITLE
Arc 1455 get linters to pass again

### PR DESCRIPTION
**Pull request by ryantimjohn**

### CODE REVIEW

**Comment by ryantimjohn** [comment]
@Frydafly @dmbluestate I'm going to have the linters automatically create a pull request to lint the files so that y'all don't have to go through the pain in the butt you went through last time.

**Comment by ryantimjohn** [comment]
@dmbluestate the PR would be automatically generated in Github Workflows, and would be a PR against the branch you're currently working on. Would be saving you a step and be similar to the workflow @Frydafly has here: https://github.com/bsd/dbt_package_updater

**Comment by ryantimjohn** [comment]
@dmbluestate here's an example of how one of these magic PRs looks; it's machine generated:
https://github.com/bsd/arc-campaigns-fairfight-dbt/pull/13

**Review by Frydafly — APPROVED** [review]
Haven't looked through it all-- am assuming all changes are formatting! Thank you

**Pull request merged**
